import torch
import os
from pathlib import Path
import wandb
import yaml
from tqdm import tqdm
from typing import Optional

from models.yolo import YOLOModel
from utils.config import YOLOConfig


class YOLOTrainer:
    def __init__(self, config: YOLOConfig):
        self.config = config
        self.device = torch.device(config.device)
        
        # Create output directory
        self.output_dir = Path('runs') / config.project_name
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Create unique run directory
        self.run_number = 0
        while (self.output_dir / f'run_{self.run_number}').exists():
            self.run_number += 1
        self.run_name = f'run_{self.run_number}'
        self.output_dir = self.output_dir / self.run_name
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Initialize wandb
        self.init_wandb()
        
        # Initialize model
        self.model = YOLOModel(config)
        
        # Training state
        self.current_epoch = 0
        self.best_map = 0.0
        
        # Save config
        self.save_config()
    
    def init_wandb(self):
        """Initialize Weights & Biases logging"""
        if self.config.wandb_mode != 'disabled':
            wandb.init(
                project=self.config.wandb_project,
                name=f"{self.config.wandb_name}_{self.run_name}",
                config=self.config.__dict__,
                mode=self.config.wandb_mode
            )
        print(f"Wandb mode: {self.config.wandb_mode}")
    
    def save_config(self):
        """Save training configuration"""
        config_path = self.output_dir / 'config.yaml'
        with open(config_path, 'w') as f:
            yaml.dump(self.config.__dict__, f, default_flow_style=False)
        print(f"Config saved to: {config_path}")
    
    def train(self):
        """Train the YOLO model"""
        print(f"Starting YOLO training for {self.config.epochs} epochs")
        print(f"Output directory: {self.output_dir}")
        
        # Train the model
        results = self.model.train(
            project=str(self.output_dir.parent),
            name=self.run_name,
        )
        
        # Get training results and log to wandb
        if self.config.wandb_mode != 'disabled':
            self.log_results(results)
        
        # Save final model
        best_model_path = self.output_dir / 'best.pt'
        last_model_path = self.output_dir / 'last.pt'
        
        # Copy the best weights from YOLO's output directory
        yolo_output_dir = self.output_dir / 'weights'
        if yolo_output_dir.exists():
            import shutil
            if (yolo_output_dir / 'best.pt').exists():
                shutil.copy2(yolo_output_dir / 'best.pt', best_model_path)
                print(f"Best model saved to: {best_model_path}")
            if (yolo_output_dir / 'last.pt').exists():
                shutil.copy2(yolo_output_dir / 'last.pt', last_model_path)
                print(f"Last model saved to: {last_model_path}")
        
        print("Training completed!")
        return results
    
    def log_results(self, results):
        """Log training results to wandb"""
        if hasattr(results, 'results_dict'):
            wandb.log(results.results_dict)
        
        # Log any CSV files generated by YOLO
        csv_files = list(self.output_dir.glob('*.csv'))
        for csv_file in csv_files:
            wandb.save(str(csv_file))
    
    def validate(self, model_path: Optional[str] = None):
        """Validate the trained model"""
        if model_path:
            # Load specific model for validation
            temp_config = self.config
            temp_config.checkpoint_path = model_path
            model = YOLOModel(temp_config)
        else:
            model = self.model
        
        print("Running validation...")
        results = model.validate()
        
        if self.config.wandb_mode != 'disabled':
            wandb.log({"val_map": results.box.map})
        
        return results
    
    def test_predictions(self, test_images_path: str, output_path: Optional[str] = None):
        """Test the model on sample images"""
        if output_path is None:
            output_path = self.output_dir / 'test_predictions'
        
        output_path = Path(output_path)
        output_path.mkdir(parents=True, exist_ok=True)
        
        test_images = list(Path(test_images_path).glob('*.png')) + \
                     list(Path(test_images_path).glob('*.jpg')) + \
                     list(Path(test_images_path).glob('*.jpeg'))
        
        print(f"Testing on {len(test_images)} images...")
        
        for image_path in tqdm(test_images, desc="Testing"):
            results = self.model.predict(str(image_path))
            
            # Save prediction
            if results and len(results) > 0:
                result = results[0]
                result.save(filename=str(output_path / f"pred_{image_path.name}"))
                
                # Log detection info
                if len(result.boxes) > 0:
                    for i, box in enumerate(result.boxes):
                        conf = box.conf.item() if hasattr(box.conf, 'item') else box.conf
                        print(f"  {image_path.name}: Detection {i+1} - Confidence: {conf:.4f}")
                else:
                    print(f"  {image_path.name}: No detections")
        
        print(f"Test predictions saved to: {output_path}")


def main():
    """Main training function"""
    # Configuration
    config = YOLOConfig(
        # Model settings
        model_type="yolo11n",
        device="cpu",
        pretrained_path="./checkpoints",
        
        # Dataset paths
        dataset_path="./sample_data/train",
        val_dataset_path="./sample_data/val",
        class_names=['scar'],
        
        # Training parameters
        epochs=10,
        batch_size=16,
        image_size=640,
        patience=50,
        
        # Augmentation (optimized for medical scars)
        mosaic=0.9,
        mixup=0.1,
        copy_paste=0.4,
        degrees=15.0,
        hsv_v=0.3,
        
        # Detection parameters
        iou_threshold=0.2,
        conf_threshold=0.15,
        max_detections=2,
        
        # Project settings
        project_name="yolo_scar_detection",
        experiment_name="enhanced_scar_detection",
        
        # Wandb settings
        wandb_project="YOLO-scar-detection",
        wandb_name="scar_detection_v1",
        wandb_mode="disabled"  # Set to "online" to enable wandb logging
    )
    
    # Create trainer
    trainer = YOLOTrainer(config)
    
    # Train the model
    results = trainer.train()
    
    # Validate the model
    val_results = trainer.validate()
    print(f"Validation mAP: {val_results.box.map:.4f}")
    
    # Test on sample images (optional)
    # trainer.test_predictions("/path/to/test/images")
    
    print("Training pipeline completed!")


if __name__ == "__main__":
    main() 